### ISSUE TITLE
Incorrect migration

### ISSUE THREAD

**Issue by vitaly-zdanevich** [pekka2/OpenCart-Migration-Upgrade-Tool#12]
My steps:

1) Clean install of Opencart 2
2) Import sql from Opencart 1.5 (ocStore) with phpMyAdmin (with ~3000 of products)
3) Copied images from old store to current
4) Run migration tool, correct steps 1-2-3 without simulation

And now at admin page and front page I not see any products. At phpMyAdmin I see products.

**Comment by pekka2** [comment]
Why do first clean install? This is migration & upgrade tool... if do clean install, delete all it tables and copy store database tables to new database.

**Comment by vitaly-zdanevich** [comment]
That's what I did, point 2: "Import sql from Opencart 1.5 (ocStore) with phpMyAdmin (with ~3000 of products)".

**Comment by pekka2** [comment]
When is image directory name? Original directory in clean install is `catalog`. Is this original directory yet there? Are you copied your product images to this directory `catalog`?

**Comment by pekka2** [comment]
Sorry, your reply I is no understand....
Is you directory image/data also new store? 
If... delete directory image/catalog and rename image/data to image/catalog.........
