### ISSUE TITLE
Warning: fopen(/converter/system/logs/error.txt): failed to open stream: No such file or directory...

### ISSUE THREAD

**Issue by elalemanyo** [pekka2/OpenCart-Migration-Upgrade-Tool#2]
Hi,

I have this error:
<code>
Warning: fopen(/converter/system/logs/error.txt): failed to open stream: No such file or directory in /converter/system/library/log.php on line 12  Warning: fwrite() expects parameter 1 to be resource, boolean given in /converter/system/library/log.php on line 14  Warning: fclose() expects parameter 1 to be resource, boolean given in /converter/system/library/log.php on line 16
</code>

Can you help me with that?

**Comment by pekka2** [comment]
Your directory `system/logs` permission must be same when yourstore.com/system/logs.

**Comment by elalemanyo** [comment]
Now I have this error: Fatal error: Call to undefined method ModelUpgradeSettings::hasSetting() in converter/model/upgrade/settings.php on line 351, can you help me with that?

Thanks!
