### ISSUE TITLE
Redirect Error

### ISSUE THREAD

**Issue by milezzz** [pekka2/OpenCart-Migration-Upgrade-Tool#22]
Not sure what the issue is...I upload /converter make sure permissions look ok but browser says:

`Too many redirects error.`

`domain.com redirected you too many times.`

Am I missing something??

**Comment by pekka2** [comment]
Are you there empty file converter/config.php? Can you remove it.

**Comment by milezzz** [comment]
Ended up buying your paid converter which worked well for us :)
