### ISSUE TITLE
Upgrade already done... can I use your tool?

### ISSUE THREAD

**Issue by elalemanyo** [pekka2/OpenCart-Migration-Upgrade-Tool#23]
Hi,
I upgrade opencart 1.5.5.1 to version 2.3.0.2 without using any special upgrade tool. For the moment is everything working good. I had some issues with extensions not working and stuff like this but I already fix them.
The only problems that I have are some permissions problems, even my user had all permissions selected sometimes I can not edit some settings from extensions and stuff like this.
Also opencart is not sending email to extra email, just send to the primary one.

Would your tool help me to fix some of those problems? Maybe you can tell me what you think.

Thanks!

**Comment by pekka2** [comment]
@elalemanyo 
I am late.
This problem  is maybe in table 'user_group'. Your need change column 'permission' type to 'mediumtext'.
Or: are you changed column 'permission' content to json format?
