### ISSUE TITLE
Duplicate Column Name status?

### ISSUE THREAD

**Issue by uglyeoin** [pekka2/OpenCart-Migration-Upgrade-Tool#3]
Notice: Error: Duplicate column name 'status'
Error No: 1060
ALTER TABLE `oc_language` ADD COLUMN status tinyint(1) NOT NULL DEFAULT 0 in ****/converter/system/database/mysql.php on line 50

**Comment by pekka2** [comment]
Will help, if you clear the cache `converter/system/cache`?

**Comment by syntaxerror** [comment]
No, it will not help to clear the cache. It's the same if it's a new start with empty cache folder.
It should not be added, as it's already there.

In file /model/upgrade/table_columns.php line 755-760:
		array(
                        'table'         => 'language',
			'field'		=> 'status',
			'type'		=> 'inyint(',
			'column'	=> ' tinyint(1) NOT NULL DEFAULT 0'
		),
