### ISSUE TITLE
DB bugs - T.ex custom fields not working after upgrade

### ISSUE THREAD

**Issue by syntaxerror** [pekka2/OpenCart-Migration-Upgrade-Tool#5]
Table 'custom_field', columns to delete: 'required' and 'position'

Table 'custom_field_customer_group', column to add: 'required'

Seems like the changes in database tables and columns need to be checked more carefully, and handled properly. Delete those not needed, and add the new ones.

**Comment by syntaxerror** [comment]
In file /model/upgrade/table_columns.php line 459-466, customer should be custom:

		array(
                        'table'         => 'customer_field',
			'field'		=> 'position'
		),
		array(
                        'table'         => 'customer_field',
			'field'		=> 'required'
		),

**Comment by syntaxerror** [comment]
In file /model/upgrade/table_columns.php add after line 58 (new 59-64):

		array(
                        'table'         => 'custom_field_customer_group',
			'field'		=> 'required',
			'type'		=> 'inyint(',
			'column'	=> ' tinyint(1) NOT NULL'
		),

**Comment by pekka2** [comment]
Hi. Rune.
That `custom_field` table`s columns is in array $delcols (this start in line 441), those deleted.
I is no found that `custom_field_customer_group`.

**Comment by syntaxerror** [comment]
There is no table named 'customer_field':
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql

But you have it here:
https://github.com/pekka2/OpenCart-Migration-Upgrade-Tool/blob/master/upload/converter/model/upgrade/table_columns.php#L455

But there is a table named oc_custom_field:
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L1210

And there is indeed a table named 'custom_field_customer_group', where it's missing a field:
https://github.com/opencart/opencart/blob/master/upload/install/opencart.sql#L1226

So you should change into:
https://github.com/syntaxerror/OpenCart-Migration-Upgrade-Tool/commit/712f611bb441e49bf1edace676b0cc821cd42b15

:)
